import { ApolloClient, InMemoryCache, createHttpLink } from '@apollo/client';

export const origins = {
  graph: 'https://graph.dev.jit.care/graphql',
};

const httpLink = createHttpLink({
  uri: origins.graph,
  headers: {
    authorization: `Bearer eyJraWQiOiIzZ1U3bzFFVkg2bTJKY3AxXC9TVWpMYTlIQUJFelluQUx6QXNPS0lLNDE4Zz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI0YzliODNhNy1hZmEzLTQ3NTEtYjYzNi0yNjE3MWNhOGU5ZDEiLCJjb2duaXRvOmdyb3VwcyI6WyJhZG1pbl82OTI2MjdlZi1mZGE4LTQyMDMtYjEwOC1lOGU5ZjUyYWQ0MTAiLCJ0ZW5hbnRfNjkyNjI3ZWYtZmRhOC00MjAzLWIxMDgtZThlOWY1MmFkNDEwIiwidGVuYW50Xzk0MGU4ZWRmLWVkZDktNDAxZC1hMjFhLTEwZjg2NmZiZGIzZiJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9VYXFsdUxPaHEiLCJ2ZXJzaW9uIjoyLCJjbGllbnRfaWQiOiIxcDNoNG1rc2ZhdWU0cThqbjQ3dWZlYm9yIiwib3JpZ2luX2p0aSI6IjIyNDZmOTNlLTNlOGEtNGZhYS1iNWZjLThkM2FkOWY2N2QwMSIsImV2ZW50X2lkIjoiMjMwZTdiYWUtODZlMS00NmM3LThkOGUtNDY3Y2FhNDY4MTc3IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJwaG9uZSBncmF2aXR5XC9ncmFwaHFsIG9wZW5pZCBlbWFpbCIsImF1dGhfdGltZSI6MTY4NzA4MDgzNSwiZXhwIjoxNjg4NzkzMDg2LCJpYXQiOjE2ODg3MDY2ODYsImp0aSI6ImRkZGRmZjllLWRkOWEtNDg3OS1hMDMzLTQ5MGU4MGZmN2UyZCIsInVzZXJuYW1lIjoiY29kZXRlc3QtdXNlciJ9.YRNgWVMvYEQ_s8LytaHQuZ7utdyjv7Y8VpsazV2U-uZ0m_OrmUSBbmOmCe4o-_I17iHsdRphy5NnYAS7Sj8PxZDWgWjf3YxF3nK4Eti8y_hMm2Zf5lMekU1fXlx9Ln33s-KQBcbxxiNABpAdDooMJpahqXiuWwc31GtCi3MWbvKTzqGmRas2iS_Z47VlslBo3k2UPsiJrQTOzEHIXNwQsQjwvWR5hEZkUv1MDXMCjBVcVb6LpM9Q8PDKKK7p8ArnP31xNKiu0GbnAherfekXdFQJDOWck9SfBfvStv73r6BqLjjQB9zW69lReRCZVVkEY4GKCI8juRAkhEVo-Xdy6g`,
  },
});

export const client = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache(),
  credentials: 'include',
});
